
name: "abi-db"

services:
  abi-db:
    type: "abi-db"
    driver: aws-s3
    region: ap-northeast-1
    bucket: abi-db
    accesskey: AKIAW4KFHVINTAKRKJUL
    secret: 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

    