// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: pb/api-db-pb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetTask) Reset() {
	*x = GetTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_db_pb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTask) ProtoMessage() {}

func (x *GetTask) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_db_pb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTask.ProtoReflect.Descriptor instead.
func (*GetTask) Descriptor() ([]byte, []int) {
	return file_pb_api_db_pb_proto_rawDescGZIP(), []int{0}
}

func (x *GetTask) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errno  int32  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data   []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetResult) Reset() {
	*x = GetResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_db_pb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResult) ProtoMessage() {}

func (x *GetResult) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_db_pb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResult.ProtoReflect.Descriptor instead.
func (*GetResult) Descriptor() ([]byte, []int) {
	return file_pb_api_db_pb_proto_rawDescGZIP(), []int{1}
}

func (x *GetResult) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *GetResult) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *GetResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PutTask) Reset() {
	*x = PutTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_db_pb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutTask) ProtoMessage() {}

func (x *PutTask) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_db_pb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutTask.ProtoReflect.Descriptor instead.
func (*PutTask) Descriptor() ([]byte, []int) {
	return file_pb_api_db_pb_proto_rawDescGZIP(), []int{2}
}

func (x *PutTask) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutTask) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errno  int32  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
}

func (x *PutResult) Reset() {
	*x = PutResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_db_pb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResult) ProtoMessage() {}

func (x *PutResult) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_db_pb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResult.ProtoReflect.Descriptor instead.
func (*PutResult) Descriptor() ([]byte, []int) {
	return file_pb_api_db_pb_proto_rawDescGZIP(), []int{3}
}

func (x *PutResult) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *PutResult) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

type MergeTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MergeTask) Reset() {
	*x = MergeTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_db_pb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeTask) ProtoMessage() {}

func (x *MergeTask) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_db_pb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeTask.ProtoReflect.Descriptor instead.
func (*MergeTask) Descriptor() ([]byte, []int) {
	return file_pb_api_db_pb_proto_rawDescGZIP(), []int{4}
}

func (x *MergeTask) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MergeTask) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MergeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errno  int32  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
}

func (x *MergeResult) Reset() {
	*x = MergeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_db_pb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeResult) ProtoMessage() {}

func (x *MergeResult) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_db_pb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeResult.ProtoReflect.Descriptor instead.
func (*MergeResult) Descriptor() ([]byte, []int) {
	return file_pb_api_db_pb_proto_rawDescGZIP(), []int{5}
}

func (x *MergeResult) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *MergeResult) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

type DelTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DelTask) Reset() {
	*x = DelTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_db_pb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTask) ProtoMessage() {}

func (x *DelTask) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_db_pb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTask.ProtoReflect.Descriptor instead.
func (*DelTask) Descriptor() ([]byte, []int) {
	return file_pb_api_db_pb_proto_rawDescGZIP(), []int{6}
}

func (x *DelTask) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DelResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errno  int32  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
}

func (x *DelResult) Reset() {
	*x = DelResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_db_pb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelResult) ProtoMessage() {}

func (x *DelResult) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_db_pb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelResult.ProtoReflect.Descriptor instead.
func (*DelResult) Descriptor() ([]byte, []int) {
	return file_pb_api_db_pb_proto_rawDescGZIP(), []int{7}
}

func (x *DelResult) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *DelResult) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

var File_pb_api_db_pb_proto protoreflect.FileDescriptor

var file_pb_api_db_pb_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x64, 0x62, 0x2d, 0x70, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x64, 0x62, 0x22, 0x1b, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x4d, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x2f, 0x0a, 0x07, 0x50, 0x75, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x39, 0x0a, 0x09, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67,
	0x22, 0x33, 0x0a, 0x09, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3b, 0x0a, 0x0b, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72,
	0x72, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d,
	0x73, 0x67, 0x22, 0x1b, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x39, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x32, 0x9b, 0x01, 0x0a, 0x07, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0b, 0x2e,
	0x64, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x0d, 0x2e, 0x64, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x21, 0x0a, 0x03, 0x50, 0x75, 0x74,
	0x12, 0x0b, 0x2e, 0x64, 0x62, 0x2e, 0x50, 0x75, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x0d, 0x2e,
	0x64, 0x62, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x27, 0x0a, 0x05,
	0x4d, 0x65, 0x72, 0x67, 0x65, 0x12, 0x0d, 0x2e, 0x64, 0x62, 0x2e, 0x4d, 0x65, 0x72, 0x67, 0x65,
	0x54, 0x61, 0x73, 0x6b, 0x1a, 0x0f, 0x2e, 0x64, 0x62, 0x2e, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x21, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x12, 0x0b, 0x2e, 0x64,
	0x62, 0x2e, 0x44, 0x65, 0x6c, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x0d, 0x2e, 0x64, 0x62, 0x2e, 0x44,
	0x65, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_api_db_pb_proto_rawDescOnce sync.Once
	file_pb_api_db_pb_proto_rawDescData = file_pb_api_db_pb_proto_rawDesc
)

func file_pb_api_db_pb_proto_rawDescGZIP() []byte {
	file_pb_api_db_pb_proto_rawDescOnce.Do(func() {
		file_pb_api_db_pb_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_api_db_pb_proto_rawDescData)
	})
	return file_pb_api_db_pb_proto_rawDescData
}

var file_pb_api_db_pb_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_api_db_pb_proto_goTypes = []interface{}{
	(*GetTask)(nil),     // 0: db.GetTask
	(*GetResult)(nil),   // 1: db.GetResult
	(*PutTask)(nil),     // 2: db.PutTask
	(*PutResult)(nil),   // 3: db.PutResult
	(*MergeTask)(nil),   // 4: db.MergeTask
	(*MergeResult)(nil), // 5: db.MergeResult
	(*DelTask)(nil),     // 6: db.DelTask
	(*DelResult)(nil),   // 7: db.DelResult
}
var file_pb_api_db_pb_proto_depIdxs = []int32{
	0, // 0: db.Service.Get:input_type -> db.GetTask
	2, // 1: db.Service.Put:input_type -> db.PutTask
	4, // 2: db.Service.Merge:input_type -> db.MergeTask
	6, // 3: db.Service.Del:input_type -> db.DelTask
	1, // 4: db.Service.Get:output_type -> db.GetResult
	3, // 5: db.Service.Put:output_type -> db.PutResult
	5, // 6: db.Service.Merge:output_type -> db.MergeResult
	7, // 7: db.Service.Del:output_type -> db.DelResult
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_api_db_pb_proto_init() }
func file_pb_api_db_pb_proto_init() {
	if File_pb_api_db_pb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_api_db_pb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_api_db_pb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_api_db_pb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_api_db_pb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_api_db_pb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_api_db_pb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_api_db_pb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_api_db_pb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_api_db_pb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_api_db_pb_proto_goTypes,
		DependencyIndexes: file_pb_api_db_pb_proto_depIdxs,
		MessageInfos:      file_pb_api_db_pb_proto_msgTypes,
	}.Build()
	File_pb_api_db_pb_proto = out.File
	file_pb_api_db_pb_proto_rawDesc = nil
	file_pb_api_db_pb_proto_goTypes = nil
	file_pb_api_db_pb_proto_depIdxs = nil
}
